
##
# Scan directories for `{PROJ}/activate.sh` files and automatically define
# `intit_project_{PROJ}` functions for them.
mercator_scan() {
	local scan_root="$1"

	read_fd_lines_to_arr <(
		find "$scan_root" -maxdepth 3  -name "activate.sh"
	)

	local script_paths=("${READ_TO_ARR_RESULT[@]}")
	for script_path in "${script_paths[@]}"; do
		proj_path=$(dirname "$script_path")
		if [[ $(basename "$proj_path") = "bin" ]]; then
			proj_path=$(dirname $(dirname "$script_path"))
		fi
		proj_name=$(basename "$proj_path")
		init_f_name="init_project_$proj_name"
		# echo "$proj_name"
		# echo "$proj_path"

		if [[ -n $(type -t "$init_f_name") ]]; then
			# Project clash
			# echo Project clash
			continue
		fi

		if [[ ! ( "$proj_name" =~ ^[a-Z0-9_]+$ ) ]]; then
			# echo Invalid project name
			continue
		fi

		# echo "defining project"

		eval "
${init_f_name}() {
	prefix_prompt '$proj_name'

	.cd '$proj_path'

	source '"$script_path"'

	.help() {
		echo 'Generated by mercator_scan'
		echo 'from script: $script_path'
	}
}
"

		register_project "$proj_name"
	done
}



read_fd_lines_to_arr() {
	READ_TO_ARR_RESULT=()
	local arg="$1"
	local line
	if [[ -r "$arg" ]]; then
		exec 3<"$arg"

		while read -u 3 line; do
			READ_TO_ARR_RESULT+=("${line}")
		done
	fi
}

